version: '3.8'

services:
  ai-workflows:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    env_file:
      - ../.env
    volumes:
      - ../workflows:/app/workflows
      - ../data:/app/data
      - ../logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a database for persistent storage
  sqlite:
    image: alpine:latest
    volumes:
      - ../data:/data
    command: sh -c "mkdir -p /data && touch /data/workflows.db"
